### ISSUE TITLE
can't create contract from user via siad

### ISSUE THREAD

**Issue by vargrant** [lukechampine/user#21]
2:    ed25519:e96501f8eedb642bcd9d315eb1c800d1e0bd4bcb3f4da8d89e9e6a22fad0b881  plumbus-1.asuscomm.com:9982             1.4.1.2   1.24631e+09  5.9050 TB          250 mS        20 SC                 75 SC                      5 SC                  0.882   111111111111111111111111111111
  1:    ed25519:7962d48088ec70f0c7c28eed10d987601684bcdeed95e37cb4779a2db3b165af  siahost1.beawesomeinstead.com:9982      1.4.1.2   3.02773e+09  3.4323 TB          2 SC          20 SC                 60 SC                      3 SC                  0.887   111111111111111111111111111111
        Pubkey                                                                    Address                                 Version  Score         Remaining Storage  Contract Fee  Price (/ TB / Month)  Collateral (/ TB / Month)  Download Price (/TB)  Uptime  Recent Scans

# ./user form 7962d480 8SC 239913 
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration
# ./user form 7962d480 8SC 235600
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration
# ./user form 7962d480 8SC 235900
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration
# ./user form 7962d480 20SC 235900
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration
# ./user form 7962d480 50SC 235900
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration
# ./user form 7962d480 60SC 235900
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration
# ./user form e96501f8 60SC 235900
Contract formation failed: FormContract: ReadResponse: communication error: renter proposed a file contract with a too-long duration

**Comment by lukechampine** [comment]
If you want to form contracts at a specific blockheight, use `@235900`. From `user form --help`:

```
Usage:
    user form hostkey funds duration [filename]
    user form hostkey funds @endheight [filename]

Forms a contract with the specified host for the specified duration with the
specified amount of funds. To specify an exact end height for the contract,
use @endheight; otherwise, the end height will be the current height plus the
supplied duration. Due to various fees, the total number of coins deducted
from the wallet may be greater than funds. Run 'user scan' on the host to see
a breakdown of these fees.
```
